from enum import Enum


class SettingName(str, Enum):
    ORGANIZATION_NAME = "ORGANIZATION_NAME"
    QR_CODE_ACCESS = "QR_CODE_ACCESS"
    DRIVER_NAME = "DRIVER_NAME"
    DRIVER_ID = "DRIVER_ID"
    DRIVER_PHONE_NUMBER = "DRIVER_PHONE_NUMBER"
    TRUCK_NUMBER = "TRUCK_NUMBER"
    CARRIER_APPROVAL_STEP = "CARRIER_APPROVAL_STEP"
    TEMPERATURE_ACKNOWLEDGEMENT = "TEMPERATURE_ACKNOWLEDGEMENT"
    EARLY_CHECK_IN_STEP = "EARLY_CHECK_IN_STEP"
    CONFIRMATION_STEP = "CONFIRMATION_STEP"


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    STANDARD = "STANDARD"


class AuditAction(str, Enum):
    TOGGLE_CHANGE = "TOGGLE_CHANGE"
    VALUE_CHANGE = "VALUE_CHANGE"
    SETTING_CREATED = "SETTING_CREATED"


class InputType(str, Enum):
    TEXT = "TEXT"
    NUMERIC = "NUMERIC"
    ALPHANUMERIC = "ALPHANUMERIC"
    TEXTAREA = "TEXTAREA"
    COMPOSITE = "COMPOSITE"
